<a href="https://colab.research.google.com/github/GreenGoose19/Next_Word_Prediction/blob/main/NLP_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
corpus=open("corpus.txt").read()

In [40]:
corpus

'Lagers and ales are two distinct categories of beer, each with its own unique characteristics and brewing processes. Lagers are typically known for their crisp and clean flavors, achieved through a cold fermentation process that uses bottom-fermenting yeast strains. This cold fermentation allows for a longer and slower maturation period, resulting in a smoother and often lighter-bodied beer. On the other hand, ales are brewed with top-fermenting yeast strains at warmer temperatures, which leads to a faster fermentation process and a wider range of flavors and aromas. Ales can vary from pale and hoppy India Pale Ales (IPAs) to rich and malty stouts, providing a diverse array of taste experiences. Both lagers and ales have their own dedicated fan bases and are enjoyed around the world, making them integral parts of the vibrant and ever-evolving world of craft beer.'

In [41]:
#preprocess the corpus
import re
corpus=corpus.lower()
clean_corpus=re.sub('[^a-z0-9]+',' ', corpus)

In [42]:
clean_corpus

'lagers and ales are two distinct categories of beer each with its own unique characteristics and brewing processes lagers are typically known for their crisp and clean flavors achieved through a cold fermentation process that uses bottom fermenting yeast strains this cold fermentation allows for a longer and slower maturation period resulting in a smoother and often lighter bodied beer on the other hand ales are brewed with top fermenting yeast strains at warmer temperatures which leads to a faster fermentation process and a wider range of flavors and aromas ales can vary from pale and hoppy india pale ales ipas to rich and malty stouts providing a diverse array of taste experiences both lagers and ales have their own dedicated fan bases and are enjoyed around the world making them integral parts of the vibrant and ever evolving world of craft beer '

In [43]:
#required libraries
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
from keras.preprocessing.text import Tokenizer
from keras.utils import to_categorical
import numpy as np

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [44]:
#tokenizing the text into words
tokens = word_tokenize(clean_corpus)
tokens

['lagers',
 'and',
 'ales',
 'are',
 'two',
 'distinct',
 'categories',
 'of',
 'beer',
 'each',
 'with',
 'its',
 'own',
 'unique',
 'characteristics',
 'and',
 'brewing',
 'processes',
 'lagers',
 'are',
 'typically',
 'known',
 'for',
 'their',
 'crisp',
 'and',
 'clean',
 'flavors',
 'achieved',
 'through',
 'a',
 'cold',
 'fermentation',
 'process',
 'that',
 'uses',
 'bottom',
 'fermenting',
 'yeast',
 'strains',
 'this',
 'cold',
 'fermentation',
 'allows',
 'for',
 'a',
 'longer',
 'and',
 'slower',
 'maturation',
 'period',
 'resulting',
 'in',
 'a',
 'smoother',
 'and',
 'often',
 'lighter',
 'bodied',
 'beer',
 'on',
 'the',
 'other',
 'hand',
 'ales',
 'are',
 'brewed',
 'with',
 'top',
 'fermenting',
 'yeast',
 'strains',
 'at',
 'warmer',
 'temperatures',
 'which',
 'leads',
 'to',
 'a',
 'faster',
 'fermentation',
 'process',
 'and',
 'a',
 'wider',
 'range',
 'of',
 'flavors',
 'and',
 'aromas',
 'ales',
 'can',
 'vary',
 'from',
 'pale',
 'and',
 'hoppy',
 'india',
 'p

In [45]:
#length of the sequence to train
train_len = 3


In [46]:
#converting the data into required sequence
text_sequences = []
for i in range(train_len,len(tokens)+1):
  seq = tokens[i-train_len:i]
  text_sequences.append(seq)


In [47]:
text_sequences

[['lagers', 'and', 'ales'],
 ['and', 'ales', 'are'],
 ['ales', 'are', 'two'],
 ['are', 'two', 'distinct'],
 ['two', 'distinct', 'categories'],
 ['distinct', 'categories', 'of'],
 ['categories', 'of', 'beer'],
 ['of', 'beer', 'each'],
 ['beer', 'each', 'with'],
 ['each', 'with', 'its'],
 ['with', 'its', 'own'],
 ['its', 'own', 'unique'],
 ['own', 'unique', 'characteristics'],
 ['unique', 'characteristics', 'and'],
 ['characteristics', 'and', 'brewing'],
 ['and', 'brewing', 'processes'],
 ['brewing', 'processes', 'lagers'],
 ['processes', 'lagers', 'are'],
 ['lagers', 'are', 'typically'],
 ['are', 'typically', 'known'],
 ['typically', 'known', 'for'],
 ['known', 'for', 'their'],
 ['for', 'their', 'crisp'],
 ['their', 'crisp', 'and'],
 ['crisp', 'and', 'clean'],
 ['and', 'clean', 'flavors'],
 ['clean', 'flavors', 'achieved'],
 ['flavors', 'achieved', 'through'],
 ['achieved', 'through', 'a'],
 ['through', 'a', 'cold'],
 ['a', 'cold', 'fermentation'],
 ['cold', 'fermentation', 'process'],


In [48]:
#converting the texts into integer sequence
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_sequences)
sequences = tokenizer.texts_to_sequences(text_sequences)
sequences

[[8, 1, 3],
 [1, 3, 5],
 [3, 5, 23],
 [5, 23, 24],
 [23, 24, 25],
 [24, 25, 4],
 [25, 4, 9],
 [4, 9, 26],
 [9, 26, 10],
 [26, 10, 27],
 [10, 27, 11],
 [27, 11, 28],
 [11, 28, 29],
 [28, 29, 1],
 [29, 1, 30],
 [1, 30, 31],
 [30, 31, 8],
 [31, 8, 5],
 [8, 5, 32],
 [5, 32, 33],
 [32, 33, 12],
 [33, 12, 13],
 [12, 13, 34],
 [13, 34, 1],
 [34, 1, 35],
 [1, 35, 14],
 [35, 14, 36],
 [14, 36, 37],
 [36, 37, 2],
 [37, 2, 15],
 [2, 15, 6],
 [15, 6, 16],
 [6, 16, 38],
 [16, 38, 39],
 [38, 39, 40],
 [39, 40, 17],
 [40, 17, 18],
 [17, 18, 19],
 [18, 19, 41],
 [19, 41, 15],
 [41, 15, 6],
 [15, 6, 42],
 [6, 42, 12],
 [42, 12, 2],
 [12, 2, 43],
 [2, 43, 1],
 [43, 1, 44],
 [1, 44, 45],
 [44, 45, 46],
 [45, 46, 47],
 [46, 47, 48],
 [47, 48, 2],
 [48, 2, 49],
 [2, 49, 1],
 [49, 1, 50],
 [1, 50, 51],
 [50, 51, 52],
 [51, 52, 9],
 [52, 9, 53],
 [9, 53, 7],
 [53, 7, 54],
 [7, 54, 55],
 [54, 55, 3],
 [55, 3, 5],
 [3, 5, 56],
 [5, 56, 10],
 [56, 10, 57],
 [10, 57, 17],
 [57, 17, 18],
 [17, 18, 19],
 [18, 19, 

In [49]:
sequences=np.asarray(sequences)

In [50]:
#vocabulary size
vocabulary_size = len(tokenizer.word_counts)+1
vocabulary_size

96

In [51]:
#trainX
train_inputs=sequences[:,:-1]


In [52]:
train_inputs

array([[ 8,  1],
       [ 1,  3],
       [ 3,  5],
       [ 5, 23],
       [23, 24],
       [24, 25],
       [25,  4],
       [ 4,  9],
       [ 9, 26],
       [26, 10],
       [10, 27],
       [27, 11],
       [11, 28],
       [28, 29],
       [29,  1],
       [ 1, 30],
       [30, 31],
       [31,  8],
       [ 8,  5],
       [ 5, 32],
       [32, 33],
       [33, 12],
       [12, 13],
       [13, 34],
       [34,  1],
       [ 1, 35],
       [35, 14],
       [14, 36],
       [36, 37],
       [37,  2],
       [ 2, 15],
       [15,  6],
       [ 6, 16],
       [16, 38],
       [38, 39],
       [39, 40],
       [40, 17],
       [17, 18],
       [18, 19],
       [19, 41],
       [41, 15],
       [15,  6],
       [ 6, 42],
       [42, 12],
       [12,  2],
       [ 2, 43],
       [43,  1],
       [ 1, 44],
       [44, 45],
       [45, 46],
       [46, 47],
       [47, 48],
       [48,  2],
       [ 2, 49],
       [49,  1],
       [ 1, 50],
       [50, 51],
       [51, 52],
       [52,  9

In [53]:
#input sequence length
seq_length=train_inputs.shape[1]
seq_length

2

In [54]:
#trainY
train_targets=sequences[:,-1]




In [55]:

train_targets

array([ 3,  5, 23, 24, 25,  4,  9, 26, 10, 27, 11, 28, 29,  1, 30, 31,  8,
        5, 32, 33, 12, 13, 34,  1, 35, 14, 36, 37,  2, 15,  6, 16, 38, 39,
       40, 17, 18, 19, 41, 15,  6, 42, 12,  2, 43,  1, 44, 45, 46, 47, 48,
        2, 49,  1, 50, 51, 52,  9, 53,  7, 54, 55,  3,  5, 56, 10, 57, 17,
       18, 19, 58, 59, 60, 61, 62, 20,  2, 63,  6, 16,  1,  2, 64, 65,  4,
       14,  1, 66,  3, 67, 68, 69, 21,  1, 70, 71, 21,  3, 72, 20, 73,  1,
       74, 75, 76,  2, 77, 78,  4, 79, 80, 81,  8,  1,  3, 82, 13, 11, 83,
       84, 85,  1,  5, 86, 87,  7, 22, 88, 89, 90, 91,  4,  7, 92,  1, 93,
       94, 22,  4, 95,  9])

In [56]:
#one hot encoding
train_targets = to_categorical(train_targets, num_classes=vocabulary_size)

In [57]:
train_targets

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

**MODEL** **BUILDING**

In [58]:

#required libraries
import torch
from torch.optim import Adam
import torch.nn as nn

In [59]:
#lstm model
class lstm(nn.Module):
    def __init__(self, vocab_size, embed_size, hidden_size):
        super().__init__()
        #simple lookup table that stores embeddings of a fixed dictionary and size.
        self.embed = nn.Embedding(vocab_size, embed_size)

        #lstm
        self.lstm = nn.LSTM(embed_size, hidden_size, num_layers=2, bidirectional=False)

        #fully connected layer
        self.linear = nn.Linear(hidden_size*seq_length,vocab_size)

    def forward(self, input_word):
        #input sequence to embeddings
        embedded = self.embed(input_word)

        #passing the embedding to lstm model
        output, hidden = self.lstm(embedded)

        #reshaping
        output=output.view(output.size(0), -1)

        #fully connected layer
        output = self.linear(output)
        return output,hidden


In [60]:
model=lstm(vocab_size=vocabulary_size,embed_size=128, hidden_size=256)


In [61]:
model

lstm(
  (embed): Embedding(96, 128)
  (lstm): LSTM(128, 256, num_layers=2)
  (linear): Linear(in_features=512, out_features=96, bias=True)
)

In [62]:
#Adam optimizer
optimizer= Adam(model.parameters(), lr=0.07)

#loss
criterion = nn.BCEWithLogitsLoss()
#training the model
def train(epoch):
    #set the model to train
    model.train()
    tr_loss=0

    #clearing the Gradients
    optimizer.zero_grad()

    #predict the output
    y_pred, (state_h, state_c) = model(torch.from_numpy(train_inputs))

    #compute the loss
    loss=criterion(y_pred,torch.from_numpy(train_targets))
    losses.append(loss)

    #backpropagate
    loss.backward()

    #update the parameters
    optimizer.step()
    tr_loss = loss.item()

    print("Epoch : ",epoch,"loss : ",loss)

In [63]:
#number of epoch
no_epoch=50
losses=[]
for epoch in range(1,no_epoch+1):
    train(epoch)

Epoch :  1 loss :  tensor(0.6932, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Epoch :  2 loss :  tensor(0.1833, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Epoch :  3 loss :  tensor(0.3825, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Epoch :  4 loss :  tensor(0.9814, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Epoch :  5 loss :  tensor(0.5652, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Epoch :  6 loss :  tensor(0.2225, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Epoch :  7 loss :  tensor(0.1565, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Epoch :  8 loss :  tensor(0.1675, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Epoch :  9 loss :  tensor(0.1701, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Epoch :  10 loss :  tensor(0.1864, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Epoch :  11 loss :  tensor(0.1944, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Epoch :  12 loss :  tensor(0.2166, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
E

**prediction**

In [64]:
def predict_next_word(text):
    #set the model to evaluation
    model.eval()

    #preprocess
    text = text.lower().strip()

    #converting the text to word tokens
    input_tokens = word_tokenize(text)

    #converting the tokens to integer sequence
    sequences = tokenizer.texts_to_sequences([input_tokens])

    #converting to array
    sequences=np.asarray(sequences)
    with torch.no_grad():
        #converting to tensor
        sequences=torch.from_numpy(sequences)
        #predicting the output
        predict,(hidden,cell)=model(sequences)

    #applying the softmax layer
    softmax = torch.exp(predict)
    prob = list(softmax.numpy())

    #index of the predict word
    predictions = np.argmax(prob)

    #converting the sequence back to word
    next_word=tokenizer.sequences_to_texts([[predictions]])
    return next_word


Example

In [74]:
#we trained our model with sequence length of 2
input_text="pale and"

In [75]:
print("Possible next word will be:")
predict_next_word(input_text)

Possible next word will be:


['ales']